name: glamgem
description: A new Flutter project

# Define environment constraints
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1  # For grid view
  provider: ^6.1.2  # Downgraded version
  image_picker: ^0.8.5+3  # For image picking (if using for virtual try-on)
  firebase_database: ^11.1.3
  # arcore_flutter_plugin: ^0.0.7+3
  ar_flutter_plugin: ^0.6.1
  camera: ^0.10.0+4
  vector_math: ^2.1.0
  # camera: ^0.11.0+2
  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Add assets, fonts, and other configurations if needed
